configs: disable bmx7 as of incompatibility to mbedtls
/usr/src/freifunk/slave/ramips-mt76x8/build/firmware/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-7.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/7.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: crypt.o: in function `cryptDhmKeyMake':
/usr/src/freifunk/slave/ramips-mt76x8/build/firmware/openwrt/build_dir/target-mipsel_24kc_musl/bmx7-r2018042501/crypt.c:191: undefined reference to `MBEDTLS_DEPRECATED_STRING_CONSTANT'
/usr/src/freifunk/slave/ramips-mt76x8/build/firmware/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-7.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/7.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: /usr/src/freifunk/slave/ramips-mt76x8/build/firmware/openwrt/build_dir/target-mipsel_24kc_musl/bmx7-r2018042501/crypt.c:195: undefined reference to `MBEDTLS_DEPRECATED_STRING_CONSTANT'

see https://github.com/bmx-routing/bmx7/issues/41