patches: disable "001-rt2x00_allow_adhoc_and_ap.patch"
this causes compilation errors
  CC [M]  /var/lib/buildbot/slaves/slave/mpc85xx-generic/build/firmware/lede/build_dir/target-powerpc_8540_musl/linux-mpc85xx_generic/backports-2017-10-06/drivers/net/wireless/ralink/rt2x00/rt2x00dev.o
/var/lib/buildbot/slaves/slave/mpc85xx-generic/build/firmware/lede/build_dir/target-powerpc_8540_musl/linux-mpc85xx_generic/backports-2017-10-06/drivers/net/wireless/ralink/rt2x00/rt2x00dev.c: In function 'rt2x00lib_set_if_combinations':
/var/lib/buildbot/slaves/slave/mpc85xx-generic/build/firmware/lede/build_dir/target-powerpc_8540_musl/linux-mpc85xx_generic/backports-2017-10-06/drivers/net/wireless/ralink/rt2x00/rt2x00dev.c:1362:11: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
  if_limit = &rt2x00dev->if_limits_ap;
           ^
cc1: some warnings being treated as errors